name: Linting
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 mypy
        pip install -e .[test,optional,schema]
    - name: Lint with flake8
      run: |
        flake8 muspy --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 muspy --count --exit-zero --statistics
    - name: Lint with mypy
      run: mypy --install-types --non-interactive muspy
