name: Testing
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest
          pip install -e .[test,optional,schema]
      - name: Install Fluidsynth
        run: |
          sudo apt-get update
          sudo apt-get install fluidsynth
      - name: Test with pytest
        run: pytest --cov="muspy/" tests/
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
